


###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "id": "1111",
  "title": "TITLE",
  "author": "AUTHOR",
  "url": "http://example.com",
  "likes": 0
}

###

GET http://localhost:3003/api/blogs

###

DELETE http://localhost:3003/api/blogs


###

DELETE http://localhost:3003/api/blogs/5a422bc61b54a676234d17fc